# Occupation

### Introduction:

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

### Step 3. Assign it to a variable called users.

In [2]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user'
users = pd.read_csv(url, sep = '|')

In [4]:
users.head(2)

   user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043

### Step 4. Discover what is the mean age per occupation

In [5]:
users.groupby(by = 'occupation').agg({'age':'mean'})

                     age
occupation
administrator  38.746835
artist         31.392857
doctor         43.571429
educator       42.010526
engineer       36.388060
entertainment  29.222222
executive      38.718750
healthcare     41.562500
homemaker      32.571429
lawyer         36.750000
librarian      40.000000
marketing      37.615385
none           26.555556
other          34.523810
programmer     33.121212
retired        63.071429
salesman       35.666667
scientist      35.548387
student        22.081633
technician     33.148148
writer         36.311111

### Step 5. Discover the Male ratio per occupation and sort it from the most to the least

In [59]:
df = users.groupby(by = ['occupation', 'gender'], as_index = True).agg({'gender':'count'}).rename(columns={'gender':'count'})
df

                      count
occupation    gender
administrator F          36
              M          43
artist        F          13
              M          15
doctor        M           7
educator      F          26
              M          69
engineer      F           2
              M          65
entertainment F           2
              M          16
executive     F           3
              M          29
healthcare    F          11
              M           5
homemaker     F           6
              M           1
lawyer        F           2
              M          10
librarian     F          29
              M          22
marketing     F          10
              M          16
none          F           4
              M           5
other         F          36
              M          69
programmer    F           6
              M          60
retired       F           1
              M          13
salesman      F           3
              M           9
scientist     F           3
              M          28
student       F          60
              M         136
technician    F           1
              M          26
writer        F          19
              M          26

In [68]:
df = users.groupby(by = ['occupation', 'gender'], as_index = True).agg({'gender':'count'}).rename(columns={'gender':'count'})
left_df = df.xs('M', level = 'gender').reset_index()
right_df = df.xs('F', level='gender').reset_index()
left_df.merge(right_df, on='occupation', how='outer').rename(columns = {'count_x':'M', 'count_y':'F'}).fillna(0).assign(total = lambda x: x['F'] + x['M']).assign(m_ratio = lambda x: round(x['M']/x['total'], 2)).sort_values(by = 'm_ratio', ascending = False).iloc[:, [0, 4]]

       occupation  m_ratio
2          doctor     1.00
4        engineer     0.97
19     technician     0.96
15        retired     0.93
6       executive     0.91
14     programmer     0.91
17      scientist     0.90
5   entertainment     0.89
9          lawyer     0.83
16       salesman     0.75
3        educator     0.73
18        student     0.69
13          other     0.66
11      marketing     0.62
20         writer     0.58
12           none     0.56
0   administrator     0.54
1          artist     0.54
10      librarian     0.43
7      healthcare     0.31
8       homemaker     0.14

### Step 6. For each occupation, calculate the minimum and maximum ages

In [71]:
users.groupby('occupation').agg({'age':['min', 'max']})

              age
              min max
occupation
administrator  21  70
artist         19  48
doctor         28  64
educator       23  63
engineer       22  70
entertainment  15  50
executive      22  69
healthcare     22  62
homemaker      20  50
lawyer         21  53
librarian      23  69
marketing      24  55
none           11  55
other          13  64
programmer     20  63
retired        51  73
salesman       18  66
scientist      23  55
student         7  42
technician     21  55
writer         18  60

### Step 7. For each combination of occupation and gender, calculate the mean age

In [74]:
users.groupby(by = ['occupation', 'gender']).agg({'age':'mean'})

                            age
occupation    gender
administrator F       40.638889
              M       37.162791
artist        F       30.307692
              M       32.333333
doctor        M       43.571429
educator      F       39.115385
              M       43.101449
engineer      F       29.500000
              M       36.600000
entertainment F       31.000000
              M       29.000000
executive     F       44.000000
              M       38.172414
healthcare    F       39.818182
              M       45.400000
homemaker     F       34.166667
              M       23.000000
lawyer        F       39.500000
              M       36.200000
librarian     F       40.000000
              M       40.000000
marketing     F       37.200000
              M       37.875000
none          F       36.500000
              M       18.600000
other         F       35.472222
              M       34.028986
programmer    F       32.166667
              M       33.216667
retired       F       70.000000
              M       62.538462
salesman      F       27.000000
              M       38.555556
scientist     F       28.333333
              M       36.321429
student       F       20.750000
              M       22.669118
technician    F       38.000000
              M       32.961538
writer        F       37.631579
              M       35.346154

### Step 8.  For each occupation present the percentage of women and men

In [76]:
left_df.merge(right_df, on='occupation', how='outer').rename(columns = {'count_x':'M', 'count_y':'F'}).fillna(0).assign(total = lambda x: x['F'] + x['M']).assign(m_ratio = lambda x: round(x['M']/x['total'], 2)).assign(f_ratio = lambda x: round(x['F']/x['total'],2)).sort_values(by = 'm_ratio', ascending = False).iloc[:, [0, 4, 5]]

       occupation  m_ratio  f_ratio
2          doctor     1.00     0.00
4        engineer     0.97     0.03
19     technician     0.96     0.04
15        retired     0.93     0.07
6       executive     0.91     0.09
14     programmer     0.91     0.09
17      scientist     0.90     0.10
5   entertainment     0.89     0.11
9          lawyer     0.83     0.17
16       salesman     0.75     0.25
3        educator     0.73     0.27
18        student     0.69     0.31
13          other     0.66     0.34
11      marketing     0.62     0.38
20         writer     0.58     0.42
12           none     0.56     0.44
0   administrator     0.54     0.46
1          artist     0.54     0.46
10      librarian     0.43     0.57
7      healthcare     0.31     0.69
8       homemaker     0.14     0.86

In [ ]:
gender_ocup = users.groupby(['occupation', 'gender']).agg({'gender': 'count'})

# create a DataFrame and apply count for each occupation
occup_count = users.groupby(['occupation']).agg('count')

# divide the gender_ocup per the occup_count and multiply per 100
occup_gender = gender_ocup.div(occup_count, level = "occupation") * 100

# present all rows from the 'gender column'
occup_gender.loc[: , 'gender']

In [77]:
gender_ocup = users.groupby(['occupation', 'gender']).agg({'gender': 'count'})
gender_ocup

                      gender
occupation    gender
administrator F           36
              M           43
artist        F           13
              M           15
doctor        M            7
educator      F           26
              M           69
engineer      F            2
              M           65
entertainment F            2
              M           16
executive     F            3
              M           29
healthcare    F           11
              M            5
homemaker     F            6
              M            1
lawyer        F            2
              M           10
librarian     F           29
              M           22
marketing     F           10
              M           16
none          F            4
              M            5
other         F           36
              M           69
programmer    F            6
              M           60
retired       F            1
              M           13
salesman      F            3
              M            9
scientist     F            3
              M           28
student       F           60
              M          136
technician    F            1
              M           26
writer        F           19
              M           26

In [78]:
# create a DataFrame and apply count for each occupation
occup_count = users.groupby(['occupation']).agg('count')
occup_count

               user_id  age  gender  zip_code
occupation
administrator       79   79      79        79
artist              28   28      28        28
doctor               7    7       7         7
educator            95   95      95        95
engineer            67   67      67        67
entertainment       18   18      18        18
executive           32   32      32        32
healthcare          16   16      16        16
homemaker            7    7       7         7
lawyer              12   12      12        12
librarian           51   51      51        51
marketing           26   26      26        26
none                 9    9       9         9
other              105  105     105       105
programmer          66   66      66        66
retired             14   14      14        14
salesman            12   12      12        12
scientist           31   31      31        31
student            196  196     196       196
technician          27   27      27        27
writer              45   45      45        45

In [80]:
occup_gender = gender_ocup.div(occup_count, level = "occupation") * 100
occup_gender

                      age      gender  user_id  zip_code
occupation    gender
administrator F       NaN   45.569620      NaN       NaN
              M       NaN   54.430380      NaN       NaN
artist        F       NaN   46.428571      NaN       NaN
              M       NaN   53.571429      NaN       NaN
doctor        M       NaN  100.000000      NaN       NaN
educator      F       NaN   27.368421      NaN       NaN
              M       NaN   72.631579      NaN       NaN
engineer      F       NaN    2.985075      NaN       NaN
              M       NaN   97.014925      NaN       NaN
entertainment F       NaN   11.111111      NaN       NaN
              M       NaN   88.888889      NaN       NaN
executive     F       NaN    9.375000      NaN       NaN
              M       NaN   90.625000      NaN       NaN
healthcare    F       NaN   68.750000      NaN       NaN
              M       NaN   31.250000      NaN       NaN
homemaker     F       NaN   85.714286      NaN       NaN
              M       NaN   14.285714      NaN       NaN
lawyer        F       NaN   16.666667      NaN       NaN
              M       NaN   83.333333      NaN       NaN
librarian     F       NaN   56.862745      NaN       NaN
              M       NaN   43.137255      NaN       NaN
marketing     F       NaN   38.461538      NaN       NaN
              M       NaN   61.538462      NaN       NaN
none          F       NaN   44.444444      NaN       NaN
              M       NaN   55.555556      NaN       NaN
other         F       NaN   34.285714      NaN       NaN
              M       NaN   65.714286      NaN       NaN
programmer    F       NaN    9.090909      NaN       NaN
              M       NaN   90.909091      NaN       NaN
retired       F       NaN    7.142857      NaN       NaN
              M       NaN   92.857143      NaN       NaN
salesman      F       NaN   25.000000      NaN       NaN
              M       NaN   75.000000      NaN       NaN
scientist     F       NaN    9.677419      NaN       NaN
              M       NaN   90.322581      NaN       NaN
student       F       NaN   30.612245      NaN       NaN
              M       NaN   69.387755      NaN       NaN
technician    F       NaN    3.703704      NaN       NaN
              M       NaN   96.296296      NaN       NaN
writer        F       NaN   42.222222      NaN       NaN
              M       NaN   57.777778      NaN       NaN