# Student Alcohol Consumption

### Introduction:

This time you will download a dataset from the UCI.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv).

### Step 3. Assign it to a variable called df.

In [5]:

df  = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv', sep = ',')

### Step 4. For the purpose of this exercise slice the dataframe from 'school' until the 'guardian' column

In [12]:
df.columns.to_list()[0:12]
df.loc[:, df.columns.to_list()[0:12]]

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother
4,GP,F,16,U,GT3,T,3,3,other,other,home,father
...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,course,other
391,MS,M,17,U,LE3,T,3,1,services,services,course,mother
392,MS,M,21,R,GT3,T,1,1,other,other,course,other
393,MS,M,18,R,LE3,T,3,2,services,other,course,mother
394,MS,M,19,U,LE3,T,1,1,other,at_home,course,father

### Step 5. Create a lambda function that will capitalize strings.

In [23]:
fun = lambda x: x.capitalize()

### Step 6. Capitalize both Mjob and Fjob

In [21]:
df[['Mjob', 'Fjob']].apply(fun, inp)

         Mjob      Fjob
0     At_home   Teacher
1     At_home     Other
2     At_home     Other
3      Health  Services
4       Other     Other
..        ...       ...
390  Services  Services
391  Services  Services
392     Other     Other
393  Services     Other
394     Other   At_home

[395 rows x 2 columns]

### Step 7. Print the last elements of the data set.

In [17]:
df.tail()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

### Step 8. Did you notice the original dataframe is still lowercase? Why is that? Fix it and capitalize Mjob and Fjob.

In [26]:
df['Mjob'] = df['Mjob'].apply(fun)
df['Fjob'] = df['Mjob'].apply(fun)

### Step 9. Create a function called majority that returns a boolean value to a new column called legal_drinker (Consider majority as older than 17 years old)

In [30]:
def majority(age):
  return age>17

In [31]:
df['legal_drinker'] = df['age'].apply(majority)

In [32]:
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,legal_drinker
0,GP,F,18,U,GT3,A,4,4,At_home,At_home,...,3,4,1,1,3,6,5,6,6,True
1,GP,F,17,U,GT3,T,1,1,At_home,At_home,...,3,3,1,1,3,4,5,5,6,False
2,GP,F,15,U,LE3,T,1,1,At_home,At_home,...,3,2,2,3,3,10,7,8,10,False
3,GP,F,15,U,GT3,T,4,2,Health,Health,...,2,2,1,1,5,2,15,14,15,False
4,GP,F,16,U,GT3,T,3,3,Other,Other,...,3,2,1,2,5,4,6,10,10,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,Services,Services,...,5,4,4,5,4,11,9,9,9,True
391,MS,M,17,U,LE3,T,3,1,Services,Services,...,4,5,3,4,2,3,14,16,16,False
392,MS,M,21,R,GT3,T,1,1,Other,Other,...,5,3,3,3,3,3,10,8,7,True
393,MS,M,18,R,LE3,T,3,2,Services,Services,...,4,1,3,4,5,0,11,12,10,True
394,MS,M,19,U,LE3,T,1,1,Other,Other,...,2,3,3,3,5,5,8,9,9,True

### Step 10. Multiply every number of the dataset by 10.
##### I know this makes no sense, don't forget it is just an exercise

In [35]:
df.select_dtypes(include='int64') * 10

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,180,40,40,20,20,0,40,30,40,10,10,30,60,50,60,60
1,170,10,10,10,20,0,50,30,30,10,10,30,40,50,50,60
2,150,10,10,10,20,30,40,30,20,20,30,30,100,70,80,100
3,150,40,20,10,30,0,30,20,20,10,10,50,20,150,140,150
4,160,30,30,10,20,0,40,30,20,10,20,50,40,60,100,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,200,20,20,10,20,20,50,50,40,40,50,40,110,90,90,90
391,170,30,10,20,10,0,20,40,50,30,40,20,30,140,160,160
392,210,10,10,10,10,30,50,50,30,30,30,30,30,100,80,70
393,180,30,20,30,10,0,40,40,10,30,40,50,0,110,120,100
394,190,10,10,10,10,0,30,20,30,30,30,50,50,80,90,90